[package]
name = "ofreg-common"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
tabled = { workspace = true }
clap = { workspace = true, features = ["derive"] }
